<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use App\Models\Question;

class QuestionSeeder extends Seeder {
    public function run() {
        $questions = [
            ['question' => '1.Cada consulta de las siguientes forma parte de una transacción implícita excepto una:', 'option_a' => 'Select', 'option_b' => 'Create proc', 'option_c' => 'Insert', 'option_d' => 'Delete', 'correct_option' => 'B'],
            ['question' => '2.Tipo de fragmentación en el que cada fragmento debe incluir la clave primaria de la tabla. Su reconstrucción se realizará con una operación de join de los fragmentos componentes:', 'option_a' => 'Vertical', 'option_b' => 'Horizontal', 'option_c' => 'Mixto', 'option_d' => 'Ninguna de las anteriores', 'correct_option' => 'A'],
            ['question' => '3.Es una ventaja de los sistemas gestores de bases de datos distribuidas:', 'option_a' => 'Costo', 'option_b' => 'Control integral', 'option_c' => 'Disponibilidad', 'option_d' => 'Experiencia de uso', 'correct_option' => 'C'],
            ['question' => '4.Se refiere a que el SGBDD puede mantener una copia de un fragmento en varios nodos diferentes:', 'option_a' => 'Diseño conceptual', 'option_b' => 'Asignación', 'option_c' => 'Replicación', 'option_d' => 'Fragmentación', 'correct_option' => 'C'],
            ['question' => '5.Es una desventaja de los sistemas gestores de bases de datos distribuidas:', 'option_a' => 'Integración', 'option_b' => 'Seguridad', 'option_c' => 'Fiabilidad', 'option_d' => 'Crecimiento', 'correct_option' => 'B'],
            ['question' => '6.Un sistema distribuido de bases de datos consiste en un conjunto de ___, cada uno de los cuales puede participar en la ejecución de transacciones que accedan a datos de una o varias de ellas:', 'option_a' => 'Base de Datos', 'option_b' => 'Tablas', 'option_c' => 'Localidades', 'option_d' => 'Fragmentos', 'correct_option' => 'C'],
            ['question' => '7.Software que permite gestionar la base de datos distribuida y hace que dicha distribución sea transparente para los usuarios:', 'option_a' => 'SGBDD', 'option_b' => 'SGBDOO', 'option_c' => 'SGBD', 'option_d' => 'SGBDR', 'correct_option' => 'A'],
            ['question' => '8.Se establecen para operaciones de sólo lectura, por ejemplo “select”', 'option_a' => 'Bloqueos de esquema', 'option_b' => 'Bloqueos actualizados', 'option_c' => 'Bloqueos compartidos', 'option_d' => 'Bloqueos de intención', 'correct_option' => 'C'],
            ['question' => '9.Se concede un bloqueo de este tipo a una transacción cuando ésta está lista para modificar los datos:', 'option_a' => 'Intención', 'option_b' => 'Exclusivo', 'option_c' => 'Inclusivo', 'option_d' => 'Esquema', 'correct_option' => 'B'],
            ['question' => '10.En ellos se almacenan los objetos del esquema de la BD (tablas, índices, etc.), pudiéndose repartir por varios ficheros:', 'option_a' => 'Tablespaces', 'option_b' => 'Base de Datos', 'option_c' => 'Tablas', 'option_d' => 'Procedimientos almacenados', 'correct_option' => 'A'],
            ['question' => '11.Establece un punto específico en donde permite hacer un rollback parcial:', 'option_a' => 'Begin Tran', 'option_b' => 'Commit Tran', 'option_c' => 'Save Tran', 'option_d' => 'Rollback Tran', 'correct_option' => 'C'],
            ['question' => '12.Hace a la transacción permanente, parte irreversible de la base de datos:', 'option_a' => 'Rollback', 'option_b' => 'Save', 'option_c' => 'Commit', 'option_d' => 'Begin', 'correct_option' => 'C'],
            ['question' => '13.Tablespace llamado ________ que se crea automáticamente al hacer la instalación de SQL Server, o al crear una BD. Contiene el diccionario de datos:', 'option_a' => 'SYSTEM', 'option_b' => 'DICTIONARY', 'option_c' => 'SYSADMIN', 'option_d' => 'USER', 'correct_option' => 'A'],
            ['question' => '14.El procedimiento almacenado que proporciona los bloqueos activos en el sistema gestor de bases de datos:', 'option_a' => 'sp_indexoption', 'option_b' => 'sp_helptext', 'option_c' => 'sp_desc', 'option_d' => 'sp_lock', 'correct_option' => 'D'],
            ['question' => '15.Son los encargados de hacer que las transacciones tengan la propiedad de aislamiento:', 'option_a' => 'Rendimientos', 'option_b' => 'Transacciones', 'option_c' => 'Bloqueos', 'option_d' => 'RollBack’s', 'correct_option' => 'C'],
            ['question' => '16.Una transacción que se ejecute con este nivel de aislamiento no será inmune a las lecturas sucias, lecturas no repetibles ni lecturas fantasma.', 'option_a' => 'Lectura de transacciones', 'option_b' => 'Lectura de datos confirmados', 'option_c' => 'Lectura repetible', 'option_d' => 'Lectura de datos no confirmados', 'correct_option' => 'D'],
            ['question' => '17.Nivel de aislamiento más restrictivo ya que aplica un bloqueo al rango de datos leídos. Proporciona, por tanto, protección ante lectura de filas fantasma.', 'option_a' => 'Repeatable read', 'option_b' => 'Snapshot', 'option_c' => 'Read uncommitted', 'option_d' => 'Serializable', 'correct_option' => 'D'],
            ['question' => '18.Con este nivel de aislamiento las consultas de la transacción en curso sólo leerán los datos confirmados antes del comienzo de la misma.', 'option_a' => 'Commit', 'option_b' => 'Read uncommitted', 'option_c' => 'Snapshot', 'option_d' => 'Rollback', 'correct_option' => 'C'],
            ['question' => '19.La transacción mantiene bloqueos compartidos durante el tiempo que dure la lectura.', 'option_a' => 'Read committed', 'option_b' => 'Rollback', 'option_c' => 'Read uncommitted', 'option_d' => 'Commit', 'correct_option' => 'A'],
            ['question' => '20.Aborta la transacción y la hace terminar en forma no exitosa, cualquier cambio que la transacción pudo hacer a la BD se deshace.', 'option_a' => 'Commit', 'option_b' => 'Rollback', 'option_c' => 'End', 'option_d' => 'Begin', 'correct_option' => 'B'],
            ['question' => '21.En una base de datos distribuida, los datos se pueden encontrar distribuidos en diferentes sitios y cada uno de estos sitios pueden contar con copias del mismo objeto, o partes de él, por ejemplo, una relación. A este tipo de distribución se le llama.', 'option_a' => 'Ionización', 'option_b' => 'Colección', 'option_c' => 'Fragmentación', 'option_d' => 'Distribución', 'correct_option' => 'C'],
            ['question' => '22.Consultas que deben ser consideradas como “todo o nada”.', 'option_a' => 'Relacionales', 'option_b' => 'SELECT’s', 'option_c' => 'INSERT’s', 'option_d' => 'Transacciones', 'correct_option' => 'D'],
            ['question' => '23.Es el concepto que habla de un conjunto de cosas actuando como una unidad.', 'option_a' => 'Bases de Datos', 'option_b' => 'Atomicidad', 'option_c' => 'Transacciones', 'option_d' => 'Copias de seguridad', 'correct_option' => 'B'],
            ['question' => '24.Los usuarios ven cada objeto de datos como lógicamente único.', 'option_a' => 'Transparencia de la fragmentación', 'option_b' => 'Transparencia de la ubicación', 'option_c' => 'Transparencia de ejecución', 'option_d' => 'Transparencia de la réplica', 'correct_option' => 'A'],
            ['question' => '25.Una tabla T se divide en subconjuntos, T1, T2, ...Tn. Los fragmentos se definen a través de una operación de selección y su reconstrucción se realizará con una operación de unión de los fragmentos componentes.', 'option_a' => 'Fragmentación Vertical', 'option_b' => 'Fragmentación Horizontal', 'option_c' => 'Fragmentación', 'option_d' => 'Fragmentación Mixta', 'correct_option' => 'B'],
            ['question' => '26.Es aquella que accede a los datos del único sitio en el cual se inició la transacción.', 'option_a' => 'Transacción Global', 'option_b' => 'Transacción Segmentada', 'option_c' => 'Transacción Local', 'option_d' => 'Transacción Unilateral', 'correct_option' => 'C'],
            ['question' => '27.Tipo de transparencia que permite la integración de varios DBMSs bajo un esquema de trabajo en común.', 'option_a' => 'Distribución', 'option_b' => 'Ejecución', 'option_c' => 'Transacción', 'option_d' => 'Heterogeneidad', 'correct_option' => 'D'],
            ['question' => '28.Tipo de transparencia en donde el usuario no sabe dónde están localizados los datos, si están replicados o particionados.', 'option_a' => 'Transacción', 'option_b' => 'Fallos', 'option_c' => 'Distribución', 'option_d' => 'Ejecución', 'correct_option' => 'C'],
            ['question' => '29.NO es un componente de las bases de datos distribuidas.', 'option_a' => 'Software y Hardware de RED', 'option_b' => 'Sistema operativo multitarea', 'option_c' => 'Estaciones de trabajo', 'option_d' => 'Procesador de transacciones', 'correct_option' => 'B'],
            ['question' => '30.Están compuestas de fragmentos de bases de datos las cuales están localizadas y replicadas en diferentes y varios sitios.', 'option_a' => 'Base de Datos Orientada a Objetos', 'option_b' => 'Base de Datos Relacionales', 'option_c' => 'Base de Datos', 'option_d' => 'Base de Datos Distribuidas', 'correct_option' => 'D'],
        ];

        foreach ($questions as $question) {
            Question::create([
                'question' => $question['question'],
                'option_a' => $question['option_a'],
                'option_b' => $question['option_b'],
                'option_c' => $question['option_c'],
                'option_d' => $question['option_d'],
                'correct_option' => $question['correct_option'],
            ]);
        }
    }
}

        /*$questions = [
            ['question' => '¿Qué son los datos no estructurados?', 'option_a' => 'Datos con un esquema predefinido', 'option_b' => 'Datos en tablas relacionales', 'option_c' => 'Datos que no tienen un esquema predefinido y pueden estar en distintos formatos', 'option_d' => 'Datos almacenados en SQL', 'correct_option' => 'C'],
            ['question' => '¿Cuál de las siguientes bases de datos es orientada a documentos?', 'option_a' => 'PostgreSQL', 'option_b' => 'MongoDB', 'option_c' => 'Oracle', 'option_d' => 'MySQL', 'correct_option' => 'B'],
            ['question' => '¿Cuál de las siguientes bases de datos es un ejemplo de clave-valor?', 'option_a' => 'MongoDB', 'option_b' => 'Redis', 'option_c' => 'Neo4j', 'option_d' => 'PostgreSQL', 'correct_option' => 'B'],
            ['question' => '¿Cuál es una característica de MongoDB?', 'option_a' => 'Almacena datos en tablas', 'option_b' => 'Almacena datos en documentos JSON/BSON', 'option_c' => 'Usa solo SQL', 'option_d' => 'No soporta escalabilidad', 'correct_option' => 'B'],
            ['question' => '¿Cuál de las siguientes bases de datos es un gestor de documentos?', 'option_a' => 'MySQL', 'option_b' => 'Neo4j', 'option_c' => 'MongoDB', 'option_d' => 'Oracle', 'correct_option' => 'C'],
            ['question' => '¿Cuál de las siguientes bases de datos es un ejemplo de base de datos de grafos?', 'option_a' => 'Neo4j', 'option_b' => 'MongoDB', 'option_c' => 'Redis', 'option_d' => 'Cassandra', 'correct_option' => 'A'],
            ['question' => '¿Qué característica define a las bases de datos clave-valor?', 'option_a' => 'Almacenan datos en tablas', 'option_b' => 'Usan JSON para almacenar documentos', 'option_c' => 'Almacenan pares clave-valor donde la clave es única', 'option_d' => 'Utilizan estructuras de grafos', 'correct_option' => 'C'],
            ['question' => '¿Para qué tipo de aplicaciones son ideales las bases de datos de grafos?', 'option_a' => 'Almacenamiento de archivos multimedia', 'option_b' => 'Análisis de redes sociales y conexiones complejas', 'option_c' => 'Gestión de bases de datos relacionales', 'option_d' => 'Manejo de sesiones', 'correct_option' => 'B'],
            ['question' => '¿En qué tipo de aplicaciones son más utilizadas las bases de datos orientadas a objetos?', 'option_a' => 'Aplicaciones que utilizan modelos de programación orientada a objetos', 'option_b' => 'Almacenamiento de logs', 'option_c' => 'Manejo de datos estructurados', 'option_d' => 'Bases de datos tradicionales', 'correct_option' => 'A'],
            ['question' => '¿Cuál de las siguientes bases de datos es orientada a objetos?', 'option_a' => 'PostgreSQL', 'option_b' => 'MongoDB', 'option_c' => 'ObjectDB', 'option_d' => 'MySQL', 'correct_option' => 'C'],
            ['question' => '¿Qué estructura de datos utilizan las bases de datos orientadas a documentos?', 'option_a' => 'Registros en tablas', 'option_b' => 'Documentos en formato JSON, BSON o XML', 'option_c' => 'Archivos CSV', 'option_d' => 'Claves y valores sin estructura', 'correct_option' => 'B'],
            ['question' => '¿Qué significa que una base de datos NoSQL sea eventualmente consistente?', 'option_a' => 'Siempre está sincronizada', 'option_b' => 'Que los datos pueden no estar sincronizados temporalmente, pero eventualmente lo estarán', 'option_c' => 'No permite concurrencia', 'option_d' => 'Requiere SQL para consultas', 'correct_option' => 'B'],
            ['question' => '¿Cuál es una ventaja clave de las bases de datos orientadas a documentos?', 'option_a' => 'Alto consumo de almacenamiento', 'option_b' => 'Requiere esquema fijo', 'option_c' => 'Permiten manejar datos semiestructurados de forma eficiente', 'option_d' => 'Solo funcionan en entornos locales', 'correct_option' => 'C'],
            ['question' => '¿Cuál de las siguientes opciones describe mejor las diferencias entre datos estructurados, semiestructurados y no estructurados?', 'option_a' => 'Todos tienen la misma estructura', 'option_b' => 'Los datos estructurados tienen un esquema rígido, los semiestructurados tienen etiquetas o metadatos, y los no estructurados no tienen formato definido', 'option_c' => 'Los datos estructurados y semiestructurados son iguales', 'option_d' => 'Los datos no estructurados solo existen en bases de datos NoSQL', 'correct_option' => 'B'],
            ['question' => '¿Qué gestor de base de datos es conocido por su rendimiento en almacenamiento de caché?', 'option_a' => 'MongoDB', 'option_b' => 'Redis', 'option_c' => 'Neo4j', 'option_d' => 'Cassandra', 'correct_option' => 'B'],
            ['question' => '¿Qué es una base de datos NoSQL?', 'option_a' => 'Un modelo de base de datos que no sigue una estructura relacional y es altamente escalable', 'option_b' => 'Un tipo de base de datos basada en SQL', 'option_c' => 'Solo permite consultas SQL', 'option_d' => 'Requiere esquema fijo', 'correct_option' => 'A'],
            ['question' => '¿Cuál de las siguientes características NO es común en las bases de datos NoSQL?', 'option_a' => 'Uso de SQL para todas las consultas', 'option_b' => 'Escalabilidad horizontal', 'option_c' => 'Alta flexibilidad', 'option_d' => 'Uso de documentos JSON/BSON', 'correct_option' => 'A'],
            ['question' => '¿Qué modelo de datos utilizan las bases de datos orientadas a grafos?', 'option_a' => 'Tablas relacionales', 'option_b' => 'Registros de clave-valor', 'option_c' => 'Nodos y relaciones', 'option_d' => 'Archivos planos', 'correct_option' => 'C'],
            ['question' => '¿Cuál de los siguientes modelos NO es un tipo de base de datos NoSQL?', 'option_a' => 'Relacional', 'option_b' => 'Clave-valor', 'option_c' => 'Documentos', 'option_d' => 'Grafos', 'correct_option' => 'A'],
            ['question' => '¿Para qué tipo de aplicaciones es ideal una base de datos clave-valor?', 'option_a' => 'Análisis de datos en redes sociales', 'option_b' => 'Aplicaciones que requieren almacenamiento de sesiones y caché', 'option_c' => 'Bases de datos científicas', 'option_d' => 'Modelado de relaciones entre datos', 'correct_option' => 'B'],
            ['question' => '¿Qué base de datos NoSQL usa Facebook para manejar su red social?', 'option_a' => 'MongoDB', 'option_b' => 'Redis', 'option_c' => 'Cassandra', 'option_d' => 'Neo4j', 'correct_option' => 'C'],
            ['question' => '¿Cuál de los siguientes ejemplos representa datos no estructurados?', 'option_a' => 'Datos en una tabla de SQL', 'option_b' => 'Un conjunto de imágenes almacenadas sin etiquetas o metadatos', 'option_c' => 'Un archivo CSV', 'option_d' => 'Datos en una hoja de cálculo', 'correct_option' => 'B']
        ];*/